### ISSUE TITLE
windows 下 ydoc serve 报错

### ISSUE THREAD

**Issue by xxssww0258** [YMFE/ydoc#27]
### YDoc 版本号: 
4.1.0

### 环境(操作系统、Node 版本、浏览器版本等信息): 
```
win10专业版
node:v10.6.0
```
### 复现步骤: 
yarn init 成功
yarn build 成功
yarn serve 报错
```
\ events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:120:28)
Emitted 'error' event at:
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:126:12)
```
### 期望结果: 
yarn serve 成功

### 补充说明: 
ydoc.js
```
module.exports = {
    title: "ydoc-plugin-jsdoc",
    description: "ydoc-plugin-jsdoc description demo",
    author: "ymfe",
    plugins: ['jsdoc'],
    pluginsConfig: {
      jsdoc: {
        files: 'src/**/*.js', // 生成文档源目录
      }
    }
}
```

**Comment by dwb1994** [comment]
operation not permitted, watch
权限问题，修改下文件夹权限试试
